import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

import UpperNavbar from "./components/UpperNavbar";
import MainNavbar from "./components/MainNavbar";
import Footer from "./components/Footer";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${manrope.className}`}>
				<UpperNavbar />
				<MainNavbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
